-- VHDL Entity IO.tristateBufferULogic.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 16:28:40 20.08.2009
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY tristateBufferULogic IS
   GENERIC( 
      delay : time := gateDelay
   );
   PORT( 
      OE   : IN     std_ulogic;
      in1  : IN     std_uLogic;
      out1 : OUT    std_uLogic
   );

-- Declarations

END tristateBufferULogic ;

