--
-- VHDL Architecture Memory.FIFO.struct
--
-- Created:
--          by - francois.francois (Aphelia)
--          at - 13:45:16 08/28/19
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

LIBRARY Memory;

ARCHITECTURE struct OF FIFO IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT FIFO_bram
   GENERIC (
      dataBitNb : positive := 8;
      depth     : positive := 8
   );
   PORT (
      write   : IN     std_ulogic ;
      clock   : IN     std_ulogic ;
      reset   : IN     std_ulogic ;
      dataOut : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      read    : IN     std_ulogic ;
      dataIn  : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      empty   : OUT    std_ulogic ;
      full    : OUT    std_ulogic 
   );
   END COMPONENT;
   COMPONENT FIFO_oneRegister
   GENERIC (
      dataBitNb : positive := 8
   );
   PORT (
      write   : IN     std_ulogic ;
      clock   : IN     std_ulogic ;
      reset   : IN     std_ulogic ;
      dataOut : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      read    : IN     std_ulogic ;
      dataIn  : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      empty   : OUT    std_ulogic ;
      full    : OUT    std_ulogic 
   );
   END COMPONENT;


BEGIN

   -- Instance port mappings.

   g0: IF depth <= 1 GENERATE
   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FIFO_oneRegister USE ENTITY Memory.FIFO_oneRegister;
   -- pragma synthesis_on

   BEGIN
      I1 : FIFO_oneRegister
         GENERIC MAP (
            dataBitNb => dataBitNb
         )
         PORT MAP (
            write   => write,
            clock   => clock,
            reset   => reset,
            dataOut => dataOut,
            read    => read,
            dataIn  => dataIn,
            empty   => empty,
            full    => full
         );
   END;
   END GENERATE g0;

   g1: IF depth > 1 GENERATE
   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : FIFO_bram USE ENTITY Memory.FIFO_bram;
   -- pragma synthesis_on

   BEGIN
      I0 : FIFO_bram
         GENERIC MAP (
            dataBitNb => dataBitNb,
            depth     => depth
         )
         PORT MAP (
            write   => write,
            clock   => clock,
            reset   => reset,
            dataOut => dataOut,
            read    => read,
            dataIn  => dataIn,
            empty   => empty,
            full    => full
         );
   END;
   END GENERATE g1;

END struct;
