--
-- VHDL Architecture OBC.gpioBankControl.struct_tristate
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 09:55:32 01.08.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY gates;
USE gates.gates.all;

LIBRARY IO;

ARCHITECTURE struct_tristate OF gpioBankControl IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT bufferUlogicVector
   GENERIC (
      dataBitNb : positive := 8;
      delay     : time     := gateDelay
   );
   PORT (
      in1  : IN     std_uLogic_vector (dataBitNb-1 DOWNTO 0);
      out1 : OUT    std_uLogic_vector (dataBitNb-1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT tristateBufferULogic
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      OE   : IN     std_ulogic ;
      in1  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : bufferUlogicVector USE ENTITY Gates.bufferUlogicVector;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : bufferUlogicVector
      GENERIC MAP (
         dataBitNb => PinNumber,
         delay     => gateDelay
      )
      PORT MAP (
         in1  => pins,
         out1 => read
      );

   g0: FOR i IN 0 TO PinNumber-1 GENERATE
   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : tristateBufferULogic USE ENTITY IO.tristateBufferULogic;
   -- pragma synthesis_on

   BEGIN
      U_0 : tristateBufferULogic
         GENERIC MAP (
            delay => gateDelay
         )
         PORT MAP (
            OE   => writeEn(i),
            in1  => write(i),
            out1 => pins(i)
         );
   END;
   END GENERATE g0;

END struct_tristate;
