-- VHDL Entity OBC.gpioPinControl.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 13:42:54 28.07.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY gpioPinControl IS
   PORT( 
      write   : IN     std_ulogic;
      writeEn : IN     std_ulogic;
      read    : OUT    std_ulogic;
      pin     : INOUT  std_ulogic
   );

-- Declarations

END gpioPinControl ;

