-- VHDL Entity OBC.SPI_SlaveSelect.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 15:01:38 28.07.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY SPI_SlaveSelect IS
   PORT( 
      SS_n        : IN     std_ulogic;
      SlaveSelect : IN     std_ulogic_vector (1 DOWNTO 0);
      SS1_n       : OUT    std_ulogic;
      SS2_n       : OUT    std_ulogic;
      SS3_n       : OUT    std_ulogic
   );

-- Declarations

END SPI_SlaveSelect ;

