-- VHDL Entity OBC.SPI_Control.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 14:38:01 02.08.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY SPI_Control IS
   GENERIC( 
      dataBitNb : integer := 8
   );
   PORT( 
      SPI1_DataOut     : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI1_MISO        : IN     std_ulogic;
      SPI1_Read        : IN     std_ulogic;
      SPI1_Select      : IN     std_ulogic_vector (1 DOWNTO 0);
      SPI1_Write       : IN     std_ulogic;
      SPI2_DataOut     : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI2_MISO        : IN     std_ulogic;
      SPI2_Read        : IN     std_ulogic;
      SPI2_Write       : IN     std_ulogic;
      SPI3_DataOut     : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI3_MISO        : IN     std_ulogic;
      SPI3_Read        : IN     std_ulogic;
      SPI3_Select      : IN     std_ulogic_vector (1 DOWNTO 0);
      SPI3_Write       : IN     std_ulogic;
      SPI4_DataOut     : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI4_MISO        : IN     std_ulogic;
      SPI4_Read        : IN     std_ulogic;
      SPI4_Select      : IN     std_ulogic_vector (1 DOWNTO 0);
      SPI4_Write       : IN     std_ulogic;
      clock            : IN     std_logic;
      reset            : IN     std_logic;
      SPI1_DataIn      : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI1_MOSI        : OUT    std_ulogic;
      SPI1_SS1_n       : OUT    std_ulogic;
      SPI1_SS2_n       : OUT    std_ulogic;
      SPI1_SS3_n       : OUT    std_ulogic;
      SPI1_endTransfer : OUT    std_logic;
      SPI1_masterFull  : OUT    std_ulogic;
      SPI1_sClk        : OUT    std_ulogic;
      SPI1_slaveEmpty  : OUT    std_ulogic;
      SPI2_DataIn      : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI2_MOSI        : OUT    std_ulogic;
      SPI2_SS1_n       : OUT    std_ulogic;
      SPI2_endTransfer : OUT    std_logic;
      SPI2_masterFull  : OUT    std_ulogic;
      SPI2_sClk        : OUT    std_ulogic;
      SPI2_slaveEmpty  : OUT    std_ulogic;
      SPI3_DataIn      : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI3_MOSI        : OUT    std_ulogic;
      SPI3_SS1_n       : OUT    std_ulogic;
      SPI3_SS2_n       : OUT    std_ulogic;
      SPI3_endTransfer : OUT    std_logic;
      SPI3_masterFull  : OUT    std_ulogic;
      SPI3_sClk        : OUT    std_ulogic;
      SPI3_slaveEmpty  : OUT    std_ulogic;
      SPI4_DataIn      : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI4_MOSI        : OUT    std_ulogic;
      SPI4_SS1_n       : OUT    std_ulogic;
      SPI4_SS2_n       : OUT    std_ulogic;
      SPI4_endTransfer : OUT    std_logic;
      SPI4_masterFull  : OUT    std_ulogic;
      SPI4_sClk        : OUT    std_ulogic;
      SPI4_slaveEmpty  : OUT    std_ulogic
   );

-- Declarations

END SPI_Control ;

