--
-- VHDL Architecture OBC.Test.struct
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 10:30:44 14.07.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;


ARCHITECTURE struct OF Test IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 5 eb5
     process(clock, reset)
     begin
       if reset = '1' then
         Led1 <= '0';
       elsif rising_edge(clock) then
         Led1 <= not Led1;
       end if;
     end process;

   -- HDL Embedded Text Block 6 eb6
     process(clock, reset)
     begin
       if reset = '1' then
         Led2 <= '0';
   	  Led3 <= '0';
   	  Led4 <= '0';
   	  Led5 <= '0';
       elsif rising_edge(clock) then
         Led2 <= '0';
   	  Led3 <= '0';
   	  Led4 <= '0';
   	  Led5 <= '0';
       end if;
     end process;


   -- Instance port mappings.

END struct;
