--
-- VHDL Architecture Board.obc_circuit.struct
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 13:43:07 12.08.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
USE ieee.std_logic_arith.all;
LIBRARY gates;
USE gates.gates.all;

LIBRARY Board;
LIBRARY OBC;
LIBRARY RiscV;

ARCHITECTURE struct OF obc_circuit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL SPI1                 : std_logic_vector(PinNumber-1 DOWNTO 0);
   SIGNAL SPI1_DataIn          : std_ulogic_vector(dataBitNb-1 DOWNTO 0);
   SIGNAL SPI1_endTransfer     : std_logic;
   SIGNAL SPI1_masterFull      : std_ulogic;
   SIGNAL SPI1_slaveEmpty      : std_ulogic;
   SIGNAL SPI2                 : std_logic_vector(PinNumber-1 DOWNTO 0);
   SIGNAL SPI2_DataIn          : std_ulogic_vector(dataBitNb-1 DOWNTO 0);
   SIGNAL SPI2_endTransfer     : std_logic;
   SIGNAL SPI2_masterFull      : std_ulogic;
   SIGNAL SPI2_slaveEmpty      : std_ulogic;
   SIGNAL SPI3                 : std_logic_vector(PinNumber-1 DOWNTO 0);
   SIGNAL SPI3_DataIn          : std_ulogic_vector(dataBitNb-1 DOWNTO 0);
   SIGNAL SPI3_endTransfer     : std_logic;
   SIGNAL SPI3_masterFull      : std_ulogic;
   SIGNAL SPI3_slaveEmpty      : std_ulogic;
   SIGNAL SPI4                 : std_logic_vector(PinNumber-1 DOWNTO 0);
   SIGNAL SPI4_DataIn          : std_ulogic_vector(dataBitNb-1 DOWNTO 0);
   SIGNAL SPI4_endTransfer     : std_logic;
   SIGNAL SPI4_masterFull      : std_ulogic;
   SIGNAL SPI4_slaveEmpty      : std_ulogic;
   SIGNAL io_gpioA_read        : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioA_write       : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioA_writeEnable : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioB_read        : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioB_write       : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioB_writeEnable : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioC_read        : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioC_write       : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioC_writeEnable : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioD_read        : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioD_write       : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_gpioD_writeEnable : std_logic_vector(31 DOWNTO 0);
   SIGNAL io_jtag_tck          : std_logic;
   SIGNAL io_jtag_tdi          : std_logic;
   SIGNAL io_jtag_tdo          : std_logic;
   SIGNAL io_jtag_tms          : std_logic;
   SIGNAL logic1               : std_uLogic;
   SIGNAL reset                : std_ulogic;
   SIGNAL resetSnch_N          : std_ulogic;
   SIGNAL resetSynch           : std_ulogic;


   -- Component Declarations
   COMPONENT DFF
   PORT (
      CLK : IN     std_uLogic ;
      CLR : IN     std_uLogic ;
      D   : IN     std_uLogic ;
      Q   : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT SPI_IO_Tristate
   GENERIC (
      dataBitNb : integer := 8;
      PinNumber : integer := 32
   );
   PORT (
      SPI_DataIn       : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI_endTransfer  : IN     std_logic ;
      SPI_masterFull   : IN     std_ulogic ;
      SPI_slaveEmpty   : IN     std_ulogic ;
      writeEnable_Risc : IN     std_logic_vector (PinNumber-1 DOWNTO 0);
      DataIn           : OUT    std_logic_vector (dataBitNb-1 DOWNTO 0);
      endTransfer      : OUT    std_uLogic ;
      masterFull       : OUT    std_uLogic ;
      slaveEmpty       : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT inverterIn
   PORT (
      in1  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT bufferUlogic
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      in1  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT SPI_Control
   GENERIC (
      dataBitNb : integer := 8
   );
   PORT (
      SPI1_DataOut     : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI1_MISO        : IN     std_ulogic ;
      SPI1_Read        : IN     std_ulogic ;
      SPI1_Select      : IN     std_ulogic_vector (1 DOWNTO 0);
      SPI1_Write       : IN     std_ulogic ;
      SPI2_DataOut     : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI2_MISO        : IN     std_ulogic ;
      SPI2_Read        : IN     std_ulogic ;
      SPI2_Write       : IN     std_ulogic ;
      SPI3_DataOut     : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI3_MISO        : IN     std_ulogic ;
      SPI3_Read        : IN     std_ulogic ;
      SPI3_Select      : IN     std_ulogic_vector (1 DOWNTO 0);
      SPI3_Write       : IN     std_ulogic ;
      SPI4_DataOut     : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI4_MISO        : IN     std_ulogic ;
      SPI4_Read        : IN     std_ulogic ;
      SPI4_Select      : IN     std_ulogic_vector (1 DOWNTO 0);
      SPI4_Write       : IN     std_ulogic ;
      clock            : IN     std_logic ;
      reset            : IN     std_logic ;
      SPI1_DataIn      : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI1_MOSI        : OUT    std_ulogic ;
      SPI1_SS1_n       : OUT    std_ulogic ;
      SPI1_SS2_n       : OUT    std_ulogic ;
      SPI1_SS3_n       : OUT    std_ulogic ;
      SPI1_endTransfer : OUT    std_logic ;
      SPI1_masterFull  : OUT    std_ulogic ;
      SPI1_sClk        : OUT    std_ulogic ;
      SPI1_slaveEmpty  : OUT    std_ulogic ;
      SPI2_DataIn      : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI2_MOSI        : OUT    std_ulogic ;
      SPI2_SS1_n       : OUT    std_ulogic ;
      SPI2_endTransfer : OUT    std_logic ;
      SPI2_masterFull  : OUT    std_ulogic ;
      SPI2_sClk        : OUT    std_ulogic ;
      SPI2_slaveEmpty  : OUT    std_ulogic ;
      SPI3_DataIn      : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI3_MOSI        : OUT    std_ulogic ;
      SPI3_SS1_n       : OUT    std_ulogic ;
      SPI3_SS2_n       : OUT    std_ulogic ;
      SPI3_endTransfer : OUT    std_logic ;
      SPI3_masterFull  : OUT    std_ulogic ;
      SPI3_sClk        : OUT    std_ulogic ;
      SPI3_slaveEmpty  : OUT    std_ulogic ;
      SPI4_DataIn      : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      SPI4_MOSI        : OUT    std_ulogic ;
      SPI4_SS1_n       : OUT    std_ulogic ;
      SPI4_SS2_n       : OUT    std_ulogic ;
      SPI4_endTransfer : OUT    std_logic ;
      SPI4_masterFull  : OUT    std_ulogic ;
      SPI4_sClk        : OUT    std_ulogic ;
      SPI4_slaveEmpty  : OUT    std_ulogic 
   );
   END COMPONENT;
   COMPONENT Test
   PORT (
      clock : IN     std_ulogic ;
      reset : IN     std_ulogic ;
      Led1  : OUT    std_logic ;
      Led2  : OUT    std_logic ;
      Led3  : OUT    std_logic ;
      Led4  : OUT    std_logic ;
      Led5  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT gpioBankControl
   GENERIC (
      PinNumber : positive := 32
   );
   PORT (
      write   : IN     std_logic_vector (PinNumber-1 DOWNTO 0);
      writeEn : IN     std_logic_vector (PinNumber-1 DOWNTO 0);
      read    : OUT    std_logic_vector (PinNumber-1 DOWNTO 0);
      pins    : INOUT  std_logic_vector (PinNumber-1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT Murax
   PORT (
      io_asyncReset        : IN     std_ulogic;
      io_gpioA_read        : IN     std_logic_vector (31 DOWNTO 0);
      io_gpioB_read        : IN     std_logic_vector (31 DOWNTO 0);
      io_gpioC_read        : IN     std_logic_vector (31 DOWNTO 0);
      io_gpioD_read        : IN     std_logic_vector (31 DOWNTO 0);
      io_jtag_tck          : IN     std_logic;
      io_jtag_tdi          : IN     std_logic;
      io_jtag_tms          : IN     std_logic;
      io_mainClk           : IN     std_ulogic;
      io_gpioA_write       : OUT    std_logic_vector (31 DOWNTO 0);
      io_gpioA_writeEnable : OUT    std_logic_vector (31 DOWNTO 0);
      io_gpioB_write       : OUT    std_logic_vector (31 DOWNTO 0);
      io_gpioB_writeEnable : OUT    std_logic_vector (31 DOWNTO 0);
      io_gpioC_write       : OUT    std_logic_vector (31 DOWNTO 0);
      io_gpioC_writeEnable : OUT    std_logic_vector (31 DOWNTO 0);
      io_gpioD_write       : OUT    std_logic_vector (31 DOWNTO 0);
      io_gpioD_writeEnable : OUT    std_logic_vector (31 DOWNTO 0);
      io_jtag_tdo          : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DFF USE ENTITY Board.DFF;
   FOR ALL : SPI_Control USE ENTITY OBC.SPI_Control;
   FOR ALL : SPI_IO_Tristate USE ENTITY Board.SPI_IO_Tristate;
   FOR ALL : Test USE ENTITY OBC.Test;
   FOR ALL : bufferUlogic USE ENTITY Gates.bufferUlogic;
   FOR ALL : gpioBankControl USE ENTITY OBC.gpioBankControl;
   FOR ALL : inverterIn USE ENTITY Board.inverterIn;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 4 eb4
   logic1 <= '1';


   -- Instance port mappings.
   I_dff : DFF
      PORT MAP (
         CLK => clock,
         CLR => reset,
         D   => logic1,
         Q   => resetSnch_N
      );
   I11 : SPI_IO_Tristate
      GENERIC MAP (
         dataBitNb => 8,
         PinNumber => 32
      )
      PORT MAP (
         SPI_DataIn       => SPI1_DataIn,
         SPI_endTransfer  => SPI1_endTransfer,
         SPI_masterFull   => SPI1_masterFull,
         SPI_slaveEmpty   => SPI1_slaveEmpty,
         writeEnable_Risc => io_gpioA_writeEnable,
         DataIn           => SPI1(15 DOWNTO 8),
         endTransfer      => SPI1(20),
         masterFull       => SPI1(17),
         slaveEmpty       => SPI1(19)
      );
   I12 : SPI_IO_Tristate
      GENERIC MAP (
         dataBitNb => 8,
         PinNumber => 32
      )
      PORT MAP (
         SPI_DataIn       => SPI2_DataIn,
         SPI_endTransfer  => SPI2_endTransfer,
         SPI_masterFull   => SPI2_masterFull,
         SPI_slaveEmpty   => SPI2_slaveEmpty,
         writeEnable_Risc => io_gpioB_writeEnable,
         DataIn           => SPI2(15 DOWNTO 8),
         endTransfer      => SPI2(20),
         masterFull       => SPI2(17),
         slaveEmpty       => SPI2(19)
      );
   I13 : SPI_IO_Tristate
      GENERIC MAP (
         dataBitNb => 8,
         PinNumber => 32
      )
      PORT MAP (
         SPI_DataIn       => SPI3_DataIn,
         SPI_endTransfer  => SPI3_endTransfer,
         SPI_masterFull   => SPI3_masterFull,
         SPI_slaveEmpty   => SPI3_slaveEmpty,
         writeEnable_Risc => io_gpioC_writeEnable,
         DataIn           => SPI3(15 DOWNTO 8),
         endTransfer      => SPI3(20),
         masterFull       => SPI3(17),
         slaveEmpty       => SPI3(19)
      );
   I14 : SPI_IO_Tristate
      GENERIC MAP (
         dataBitNb => 8,
         PinNumber => 32
      )
      PORT MAP (
         SPI_DataIn       => SPI4_DataIn,
         SPI_endTransfer  => SPI4_endTransfer,
         SPI_masterFull   => SPI4_masterFull,
         SPI_slaveEmpty   => SPI4_slaveEmpty,
         writeEnable_Risc => io_gpioD_writeEnable,
         DataIn           => SPI4(15 DOWNTO 8),
         endTransfer      => SPI4(20),
         masterFull       => SPI4(17),
         slaveEmpty       => SPI4(19)
      );
   I_inv1 : inverterIn
      PORT MAP (
         in1  => reset_N,
         out1 => reset
      );
   I_inv2 : inverterIn
      PORT MAP (
         in1  => resetSnch_N,
         out1 => resetSynch
      );
   I6 : bufferUlogic
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => SPI1_MISO,
         out1 => SPI1_unused
      );
   I7 : bufferUlogic
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => SPI2_MISO,
         out1 => SPI2_unused
      );
   I8 : bufferUlogic
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => SPI3_MISO,
         out1 => SPI3_unused
      );
   I9 : bufferUlogic
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => SPI4_MISO,
         out1 => SPI4_unused
      );
   U_0 : bufferUlogic
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => fpgaIO0,
         out1 => io_jtag_tms
      );
   U_1 : bufferUlogic
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => fpgaIO1,
         out1 => io_jtag_tdi
      );
   U_5 : bufferUlogic
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => fpgaIO2,
         out1 => io_jtag_tck
      );
   U_6 : bufferUlogic
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => io_jtag_tdo,
         out1 => fpgaIO3
      );
   I0 : SPI_Control
      GENERIC MAP (
         dataBitNb => 8
      )
      PORT MAP (
         SPI1_DataOut     => SPI1(7 DOWNTO 0),
         SPI1_MISO        => SPI1_MISO,
         SPI1_Read        => SPI1(18),
         SPI1_Select      => SPI1(22 DOWNTO 21),
         SPI1_Write       => SPI1(16),
         SPI2_DataOut     => SPI2(7 DOWNTO 0),
         SPI2_MISO        => SPI2_MISO,
         SPI2_Read        => SPI2(18),
         SPI2_Write       => SPI2(16),
         SPI3_DataOut     => SPI3(7 DOWNTO 0),
         SPI3_MISO        => SPI3_MISO,
         SPI3_Read        => SPI3(18),
         SPI3_Select      => SPI3(22 DOWNTO 21),
         SPI3_Write       => SPI3(16),
         SPI4_DataOut     => SPI4(7 DOWNTO 0),
         SPI4_MISO        => SPI4_MISO,
         SPI4_Read        => SPI4(18),
         SPI4_Select      => SPI4(22 DOWNTO 21),
         SPI4_Write       => SPI4(16),
         clock            => clock,
         reset            => resetSynch,
         SPI1_DataIn      => SPI1_DataIn,
         SPI1_MOSI        => SPI1_MOSI,
         SPI1_SS1_n       => SPI1_SS1_n,
         SPI1_SS2_n       => SPI1_SS2_n,
         SPI1_SS3_n       => SPI1_SS3_n,
         SPI1_endTransfer => SPI1_endTransfer,
         SPI1_masterFull  => SPI1_masterFull,
         SPI1_sClk        => SPI1_sClk,
         SPI1_slaveEmpty  => SPI1_slaveEmpty,
         SPI2_DataIn      => SPI2_DataIn,
         SPI2_MOSI        => SPI2_MOSI,
         SPI2_SS1_n       => SPI2_SS1_n,
         SPI2_endTransfer => SPI2_endTransfer,
         SPI2_masterFull  => SPI2_masterFull,
         SPI2_sClk        => SPI2_sClk,
         SPI2_slaveEmpty  => SPI2_slaveEmpty,
         SPI3_DataIn      => SPI3_DataIn,
         SPI3_MOSI        => SPI3_MOSI,
         SPI3_SS1_n       => SPI3_SS1_n,
         SPI3_SS2_n       => SPI3_SS2_n,
         SPI3_endTransfer => SPI3_endTransfer,
         SPI3_masterFull  => SPI3_masterFull,
         SPI3_sClk        => SPI3_sClk,
         SPI3_slaveEmpty  => SPI3_slaveEmpty,
         SPI4_DataIn      => SPI4_DataIn,
         SPI4_MOSI        => SPI4_MOSI,
         SPI4_SS1_n       => SPI4_SS1_n,
         SPI4_SS2_n       => SPI4_SS2_n,
         SPI4_endTransfer => SPI4_slaveEmpty,
         SPI4_masterFull  => SPI4_masterFull,
         SPI4_sClk        => SPI4_sClk,
         SPI4_slaveEmpty  => SPI4_endTransfer
      );
   I1 : Test
      PORT MAP (
         clock => clock,
         reset => resetSynch,
         Led1  => Led1,
         Led2  => Led2,
         Led3  => Led3,
         Led4  => Led4,
         Led5  => Led5
      );
   I2 : gpioBankControl
      GENERIC MAP (
         PinNumber => 32
      )
      PORT MAP (
         write   => io_gpioA_write,
         writeEn => io_gpioA_writeEnable,
         read    => io_gpioA_read,
         pins    => SPI1
      );
   I3 : gpioBankControl
      GENERIC MAP (
         PinNumber => 32
      )
      PORT MAP (
         write   => io_gpioB_write,
         writeEn => io_gpioB_writeEnable,
         read    => io_gpioB_read,
         pins    => SPI2
      );
   I4 : gpioBankControl
      GENERIC MAP (
         PinNumber => 32
      )
      PORT MAP (
         write   => io_gpioC_write,
         writeEn => io_gpioC_writeEnable,
         read    => io_gpioC_read,
         pins    => SPI3
      );
   I5 : gpioBankControl
      GENERIC MAP (
         PinNumber => 32
      )
      PORT MAP (
         write   => io_gpioD_write,
         writeEn => io_gpioD_writeEnable,
         read    => io_gpioD_read,
         pins    => SPI4
      );
   I10 : Murax
      PORT MAP (
         io_asyncReset        => reset,
         io_mainClk           => clock,
         io_jtag_tms          => io_jtag_tms,
         io_jtag_tdi          => io_jtag_tdi,
         io_jtag_tdo          => io_jtag_tdo,
         io_jtag_tck          => io_jtag_tck,
         io_gpioA_read        => io_gpioA_read,
         io_gpioA_write       => io_gpioA_write,
         io_gpioA_writeEnable => io_gpioA_writeEnable,
         io_gpioB_read        => io_gpioB_read,
         io_gpioB_write       => io_gpioB_write,
         io_gpioB_writeEnable => io_gpioB_writeEnable,
         io_gpioC_read        => io_gpioC_read,
         io_gpioC_write       => io_gpioC_write,
         io_gpioC_writeEnable => io_gpioC_writeEnable,
         io_gpioD_read        => io_gpioD_read,
         io_gpioD_write       => io_gpioD_write,
         io_gpioD_writeEnable => io_gpioD_writeEnable
      );

END struct;
