-- VHDL Entity SPI.spiFifo.symbol
--
-- Created:
--          by - silvan.zahno.UNKNOWN (WE6996)
--          at - 07:39:39 11.11.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

ENTITY spiFifo IS
   GENERIC( 
      dataBitNb      : positive   := 8;
      fifoDepth      : positive   := 8;      --Max nbr of sequential transfers
      spiClockPeriod : positive   := 1;      --SPI clock divider
      spiFramePeriod : positive   := 1;      --SPI Inter Frame Gap
      cPol           : std_ulogic := '0';
      cPha           : std_ulogic := '0'
   );
   PORT( 
      slaveRd     : IN     std_ulogic;
      slaveData   : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      clock       : IN     std_ulogic;
      MISO        : IN     std_ulogic;
      reset       : IN     std_ulogic;
      MOSI        : OUT    std_ulogic;
      slaveEmpty  : OUT    std_ulogic;
      masterFull  : OUT    std_ulogic;
      masterData  : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      masterWr    : IN     std_ulogic;
      sClk        : OUT    std_ulogic;
      endTransfer : OUT    std_logic;
      SS_n        : OUT    std_ulogic
   );

-- Declarations

END spiFifo ;

