-- VHDL Entity SPI.spiTimer.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 13:39:54 31.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;

ENTITY spiTimer IS
   GENERIC( 
      clockPeriod : positive := 1;
      framePeriod : positive := 1
   );
   PORT( 
      en2x      : OUT    std_ulogic;
      clock     : IN     std_ulogic;
      reset     : IN     std_ulogic;
      sendFrame : OUT    std_ulogic
   );

-- Declarations

END spiTimer ;

