-- VHDL Entity SPI.spiWrite.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 13:39:54 31.10.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY spiWrite IS
   GENERIC( 
      dataBitNb : positive := 8
   );
   PORT( 
      reset          : IN     std_ulogic;
      clock          : IN     std_ulogic;
      dataOut        : IN     std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      dataOutEmpty   : IN     std_ulogic;
      dataOutEnabled : OUT    std_ulogic_vector (dataBitNb-1 DOWNTO 0);
      dataOutRd      : OUT    std_ulogic;
      busy           : IN     std_ulogic;
      sendFrame      : IN     std_ulogic;
      dataWr         : OUT    std_ulogic
   );

-- Declarations

END spiWrite ;

