-- VHDL Entity Gates.bufferUlogicVector.symbol
--
-- Created:
--          by - student.UNKNOWN (DESKTOP-3I0F3HP)
--          at - 13:19:44 14.07.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;

ENTITY bufferUlogicVector IS
   GENERIC( 
      dataBitNb : positive := 8;
      delay     : time     := gateDelay
   );
   PORT( 
      in1  : IN     std_uLogic_vector (dataBitNb-1 DOWNTO 0);
      out1 : OUT    std_uLogic_vector (dataBitNb-1 DOWNTO 0)
   );

-- Declarations

END bufferUlogicVector ;

